#!/usr/bin/env bash

if [ "$RUNTIME_LOG_LEVEL" -le 2 ]; then
echo "
-------------------------------------
Runtime Info
-------------------------------------
User:       ${RUNTIME_USER} (uid: $(id -u $RUNTIME_USER))
Group:      ${RUNTIME_GROUP} (gid: $(id -g $RUNTIME_USER))
Workdir:    ${RUNTIME_WORKDIR}
-------------------------------------
"
fi