on:
  workflow_call:
    inputs:
      tests:
        required: false
        type: string
        default: ''

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from branch name
        run: |
          export BRANCH=${GITHUB_REF##*/}
          echo "VERSION=v${BRANCH/.x/}" >> $GITHUB_ENV

      - name: Build test image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          load: true
          pull: true
          tags: ghcr.io/sitepilot/runtime:build
          cache-from: type=gha,scope=runtime-${{ env.VERSION }}

      - name: Run unit tests
        run: ${{ inputs.tests }}
        if: ${{ inputs.tests != '' }}

      - name: Build and publish image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          push: ${{ github.event_name != 'pull_request' }}
          tags:  ghcr.io/sitepilot/runtime:${{ env.VERSION }}
          platforms: linux/amd64, linux/arm64
          provenance: false
          cache-to: type=gha,mode=max,scope=runtime-${{ env.VERSION }}
