name: build

on:
  push:
    branches:
      - build
  schedule:
    - cron: '0 0 * * *'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      DOCKER_TAGS: |
        ghcr.io/sitepilot/runtime:1.x,
        ghcr.io/sitepilot/runtime:latest
      DOCKER_PULL_TAGS: |
        ghcr.io/sitepilot/runtime:pull-${{ github.event.pull_request.number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ github.event_name == 'pull_request' && env.PULL_TAGS || env.DOCKER_TAGS }}
          platforms: linux/amd64, linux/arm64
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
